name: "Terraform Deploy"

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./task1

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_region: "us-central1"
      TF_VAR_zone: "us-central1-a"
      TF_VAR_vm_name: "yablonskyi-minikube-node"
      TF_VAR_vpc_name: "yablonskyi-vpc"
      TF_VAR_subnet_name: "yablonskyi-subnet"
      TF_VAR_firewall_name: "yablonskyi-firewall"
      TF_VAR_subnet_cidr: "10.10.10.0/24"
      TF_VAR_machine_type: "e2-medium"
      TF_VAR_disk_size: "20"
      TF_VAR_image: "ubuntu-os-cloud/ubuntu-2404-lts-amd64"
      TF_VAR_state_bucket: "terraform-state-lab3-devops2"
      TF_VAR_bucket_name: "yablonskyi-bucket"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Get Instance IP
        id: get_ip
        run: |
          VM_IP=$(terraform output -raw vm_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      - name: Save IP Address
        run: echo "$(terraform output -raw vm_ip)" > vm_ip.txt

      - name: Upload IP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-ip
          path: terraform/vm_ip.txt
