name: "Ansible Software Deployment"

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types: [completed]
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download IP Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-ip
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      - name: Set IP Variable
        run: echo "VM_IP=$(cat vm_ip.txt)" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts

      - name: Ansible Pre-install Check
        run: |
          ansible-playbook task2/playbook.yml \
            -i "${{ env.VM_IP }}," \
            -u ubuntu \
            --private-key ~/.ssh/id_rsa \
            --check \
            --diff

      - name: Ansible Real Install
        run: |
          ansible-playbook task2/playbook.yml \
            -i "${{ env.VM_IP }}," \
            -u ubuntu \
            --private-key ~/.ssh/id_rsa
